### ISSUE TITLE
oh noooo

### ISSUE THREAD

**Issue by illogicalapple** [wasteofplus/wasteof.plus#79] opened 2023-08-05 02:31 UTC
![image](https://github.com/imadeanaccount1/wasteof.plus/assets/80916557/d0d3003a-0983-42a8-8f86-be18daa8bc13)
what

**Comment by imadeanaccount1** [comment] 2023-08-05 13:16
@illogicalapple Yes, this can happen and is also fixed by #66 (try the version in the artifact of [this Action] for a potential fix (https://github.com/imadeanaccount1/wasteof.plus/actions/runs/5767804066)). Thank you so much for beta testing, though!

**Comment by imadeanaccount1** [comment] 2023-08-11 01:20
Closing this as duplicate of #66

**Closed by imadeanaccount1** 2023-08-11 01:20 UTC
Labels: bug
