### ISSUE TITLE
Pop up is styleless on Firefox

### ISSUE THREAD

**Issue by Gilbert189** [wasteofplus/wasteof.plus#104] opened 2023-08-13 08:10 UTC
This is on my fork which I'd synced recently. On Firefox, it looks like... this.

![Screenshot_2023-08-13_15-02-35](https://github.com/wasteofplus/wasteof.plus/assets/57717273/f92d0e9e-8826-4415-8fbd-1057e2dd9180)

It also doesn't overflow correctly (scrolling still clips the list), although I can't demonstrate it here.

**Comment by imadeanaccount1** [comment] 2023-08-13 13:08
You have to run `npm ci` to install the styling dependencies! (Also, if you want to download a version that comes pre-built, look for the latest version labeled firefox on [this page ](https://github.com/wasteofplus/wasteof.plus/actions)). 

The main branch doesn't support Firefox. Only the `new_firefox_port` branch does at the moment. You can check out #68 which shows my progress in porting, though!

**Comment by imadeanaccount1** [comment] 2023-08-13 13:09
Closing this as a duplicate of #85 and #48. (also, it's a dependency issue)

**Closed by imadeanaccount1** 2023-08-13 13:09 UTC
